# %%
# Imports
from pathlib import Path

import numpy as np
import pandas as pd

# %%
# Crear DataFrame

data = {
    "RUT": [
        "21.344.556-7",
        "20.988.123-k",
        "22.112.443-4",
        "21.554.332-1",
        "20.776.554-9",
        "21.221.998-0",
        "22.443.112-5",
        "20.332.887-6",
        "21.665.443-2",
        "21.332.776-k",
        "22.554.110-3",
        "21.887.223-4",
        "20.443.998-1",
        "21.990.554-7",
        "22.221.334-0",
        "20.665.112-8",
        "21.443.887-5",
        "20.887.443-2",
        "22.332.110-k",
        "21.112.665-4",
        "20.554.332-9",
        "21.776.998-1",
        "22.665.221-7",
        "20.221.554-3",
        "21.332.776-k",
        "21.990.554-7",
        "22.112.887-4",
        "21.554.665-1",
        "20.776.332-9",
        "21.221.443-0",
        "21.002.334-5",
        "20.881.442-k",
        "22.109.887-3",
        "21.554.221-8",
        "20.332.112-9",
        "21.667.443-0",
        "22.445.667-1",
        "20.112.998-k",
        "22.109.887-3",
        "22.334.556-2",
        "21.112.443-7",
        "20.556.778-9",
        "22.109.887-3",
        "22.667.889-5",
        "21.223.445-0",
        "20.998.112-3",
        "22.110.554-1",
        "21.556.998-4",
        "20.778.332-6",
        "21.221.776-k",
        "22.443.887-2",
        "20.334.110-8",
        "21.669.223-5",
        "22.556.112-7",
        "21.887.443-1",
        "22.332.990-k",
        "21.114.665-4",
        "20.558.112-9",
        "22.109.887-3",
        "22.669.332-8",
    ],
    "Nombre": [
        "Martina",
        "Benjamín",
        "Sofía",
        "Mateo",
        "Florencia",
        "Lucas",
        "Isabella",
        "Joaquín",
        "Agustina",
        "Catalina",
        "Valentina",
        "Matías",
        "Elena",
        "Tomás",
        "Josefa",
        "Diego",
        "Emilia",
        "Maximiliano",
        "Isidora",
        "Felipe",
        "Antonella",
        "Samuel",
        "Fernanda",
        "Francisco",
        "Catalina",
        "Tomás",
        "Maite",
        "Benjamín",
        "Constanza",
        "Vicente",
        "Matías",
        "Javiera",
        "Rodrigo",
        "Constanza",
        "Sebastián",
        "Antonia",
        "Ignacio",
        "Fernanda",
        "Rodrigo",
        "Valentina",
        "Benjamín",
        "Isidora",
        "Rodrigo",
        "Maite",
        "Diego",
        "Emilia",
        "Maximiliano",
        "Sofía",
        "Joaquín",
        "Catalina",
        "Felipe",
        "Antonella",
        "Samuel",
        "Martina",
        "Vicente",
        "Josefa",
        "Francisco",
        "Elena",
        "Rodrigo",
        "Claudia",
    ],
    "Apellido P.": [
        "Lagos",
        "Oyarzún",
        "Cárdenas",
        "Vargas",
        "Muñoz",
        "Paredes",
        "Barrientos",
        "Aguilar",
        "Espinoza",
        "Rivas",
        "Ulloa",
        "Gómez",
        "Guerrero",
        "Almonacid",
        "Villarroel",
        "Jara",
        "Gallardo",
        "Cárcamo",
        "Bórquez",
        "Arriagada",
        "Saldivia",
        "Carrasco",
        "Henríquez",
        "Orellana",
        "Rivas",
        "Almonacid",
        "Figueroa",
        "Leiva",
        "Mena",
        "Pino",
        "Schwaner",
        "Cárcamo",
        "Paredes",
        "Vera",
        "Aguilar",
        "González",
        "Martínez",
        "Oyarzo",
        "Paredes",
        "Rojas",
        "Morales",
        "Muñoz",
        "Paredes",
        "Vargas",
        "Fuentes",
        "Santana",
        "Bravo",
        "Maldonado",
        "Carrasco",
        "Bórquez",
        "Arriagada",
        "Saldivia",
        "Henríquez",
        "Rivas",
        "Figueroa",
        "Leiva",
        "Mena",
        "Pino",
        "Paredes",
        "Cáceres",
    ],
    "Apellido M.": [
        "Silva",
        "Ruiz",
        "Mansilla",
        "González",
        "Soto",
        "Vidal",
        "Díaz",
        "Torres",
        "Mora",
        "Salinas",
        "Rojas",
        "Ibáñez",
        "Castro",
        "Bahamonde",
        "Núñez",
        np.nan,
        "Pardo",
        "Ojeda",
        "Delgado",
        "Saavedra",
        "Valenzuela",
        "Godoy",
        "Méndez",
        "Tapia",
        "Salinas",
        "Bahamonde",
        "Maturana",
        "Donoso",
        "Palma",
        "Ortiz",
        "Werner",
        "Mansilla",
        "Soto",
        "Ruiz",
        "Bahamonde",
        "Ojeda",
        "Silva",
        "Vidal",
        "Soto",
        "Espinoza",
        "Pardo",
        "Lagos",
        "Soto",
        "Núñez",
        "Palma",
        "Reyes",
        "Donoso",
        "Jara",
        "Guerra",
        "Delgado",
        "Salinas",
        "Maturana",
        "Godoy",
        "Farías",
        "Ortiz",
        "Tapia",
        "Loyola",
        "Villalobos",
        "Soto",
        "Bustos",
    ],
    "Sexo": [
        "F",
        "M",
        "F",
        np.nan,
        "F",
        "M",
        "F",
        "M",
        "F",
        "F",
        "F",
        "M",
        "F",
        "M",
        "F",
        "M",
        "F",
        "M",
        np.nan,
        "M",
        "F",
        "M",
        "F",
        "M",
        "F",
        "M",
        "F",
        "M",
        "F",
        "M",
        "M",
        "F",
        "M",
        "F",
        "M",
        "F",
        "M",
        "F",
        "M",
        "F",
        "M",
        "F",
        "M",
        np.nan,
        "M",
        "F",
        "M",
        "F",
        np.nan,
        "F",
        "M",
        "F",
        "M",
        "F",
        "M",
        "F",
        "M",
        "F",
        "M",
        "F",
    ],
    "Edad": [
        18,
        19,
        17,
        18,
        20,
        18,
        17,
        21,
        np.nan,
        18,
        17,
        18,
        20,
        18,
        17,
        19,
        18,
        20,
        17,
        18,
        19,
        18,
        17,
        21,
        18,
        18,
        17,
        18,
        20,
        18,
        19,
        20,
        17,
        18,
        21,
        18,
        17,
        19,
        17,
        17,
        18,
        20,
        17,
        17,
        19,
        np.nan,
        17,
        18,
        20,
        18,
        17,
        np.nan,
        18,
        17,
        18,
        17,
        19,
        20,
        17,
        17,
    ],
    "Ciudad": [
        "Puerto Montt",
        "Osorno",
        "Castro",
        "Puerto Varas",
        "Ancud",
        "Frutillar",
        "Quellón",
        "Llanquihue",
        "Calbuco",
        "Castro",
        "Chonchi",
        "Puerto Montt",
        "Osorno",
        "Castro",
        "Puerto Varas",
        "Ancud",
        "Frutillar",
        "Quellón",
        "Llanquihue",
        "Calbuco",
        "Purranque",
        "Chonchi",
        "Puerto Montt",
        "Osorno",
        "Castro",
        "Castro",
        "Ancud",
        "Frutillar",
        "Quellón",
        "Llanquihue",
        "Puerto Varas",
        "Castro",
        "Osorno",
        "Puerto Montt",
        "Ancud",
        "Quellón",
        "Frutillar",
        "Calbuco",
        "Osorno",
        "Purranque",
        "Chonchi",
        "Fresia",
        "Osorno",
        "San Pablo",
        "Cochamó",
        "Puerto Octay",
        "Los Muermos",
        "Maullín",
        "Hualaihué",
        "Dalcahue",
        "Curaco de Vélez",
        "Quinchao",
        "Puqueldón",
        "Queilén",
        "San Juan de la Costa",
        "Río Negro",
        "Puerto Montt",
        "Osorno",
        "Osorno",
        "Puerto Varas",
    ],
    "Promedio": [
        6.5,
        5.8,
        6.2,
        4.5,
        5.9,
        6.8,
        5.4,
        6.1,
        4.9,
        6.1,
        6.7,
        5.5,
        6.0,
        4.2,
        6.9,
        5.7,
        6.3,
        5.1,
        6.6,
        4.8,
        5.6,
        6.4,
        5.3,
        5.9,
        6.1,
        4.2,
        6.8,
        5.0,
        np.nan,
        5.4,
        6.1,
        5.4,
        4.9,
        6.7,
        5.2,
        5.8,
        6.3,
        4.5,
        4.9,
        6.0,
        5.6,
        6.9,
        4.9,
        6.2,
        np.nan,
        6.5,
        4.8,
        5.3,
        6.6,
        5.9,
        4.1,
        5.5,
        6.4,
        np.nan,
        4.7,
        5.2,
        6.1,
        5.0,
        4.9,
        6.3,
    ],
}

df = pd.DataFrame(data)
print(df)

# %%
# Preparar los datos

print("Tipos de datos:")
print(df.dtypes)

print("Valores nulos por columna:")
print(df.isnull().sum())

print("Cantidad de filas duplicadas:", df.duplicated().sum())
df = df.drop_duplicates()

df["Edad"] = pd.to_numeric(df["Edad"], errors="coerce")
df["Promedio"] = pd.to_numeric(df["Promedio"], errors="coerce")
df["Promedio"] = df["Promedio"].interpolate()

print("DataFrame limpio:")
print(df)

# %%
# Lista de alumnos mayores de 20 años de Puerto Montt

alumnos_puerto_montt_mayores_20 = df[
    (df["Edad"] > 20) & (df["Ciudad"] == "Puerto Montt")
]

print("Alumnos mayores de 20 años de Puerto Montt:")
print(alumnos_puerto_montt_mayores_20)

# %%
# Listado de alumnos de sexo femenino

alumnas = df[df["Sexo"] == "F"]
print("Alumnas de sexo femenino:")
print(alumnas)

# %%
# Cantidad de alumnos de la ciudad de Quellón

cantidad_quellon = df[df["Ciudad"] == "Quellón"].shape[0]
print("Cantidad de alumnos de Quellón:", cantidad_quellon)

# %%
# Todas las alumnas de nombre Catalina, Sara

alumnas_catalina_sara = df[(df["Sexo"] == "F") & (df["Nombre"].isin(["Catalina", "Sara"]))]
print("Alumnas de nombre Catalina o Sara:")
print(alumnas_catalina_sara)

# %%
# Alumnos que su ciudad comience con la letra P

alumnos_ciudad_p = df[df["Ciudad"].str.startswith("P")]
print("Alumnos con ciudad que comienza con P:")
print(alumnos_ciudad_p)

# %%
# Guardar datos en CSV

output_path = Path(__file__).with_name("alumnos_limpios.csv")
df.to_csv(output_path, index=False)

print("Archivo guardado en:", output_path)
