PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS Hechos_Ventas;
DROP TABLE IF EXISTS Dim_Pelicula;
DROP TABLE IF EXISTS Dim_Sucursal;
DROP TABLE IF EXISTS Dim_Tiempo;

CREATE TABLE Dim_Pelicula (
    ID_Pelicula INTEGER NOT NULL PRIMARY KEY,
    Titulo TEXT NOT NULL,
    Genero TEXT NOT NULL,
    Clasificacion TEXT NOT NULL
);

CREATE TABLE Dim_Sucursal (
    ID_Sucursal INTEGER NOT NULL PRIMARY KEY,
    Nombre_Cine TEXT NOT NULL,
    Ciudad TEXT NOT NULL,
    Pais TEXT NOT NULL
);

CREATE TABLE Dim_Tiempo (
    ID_Tiempo INTEGER NOT NULL PRIMARY KEY,
    Fecha TEXT NOT NULL,
    Dia INTEGER NOT NULL,
    Mes INTEGER NOT NULL,
    Anio INTEGER NOT NULL,
    Trimestre INTEGER NOT NULL
);
